image: src.ent.ea.com:8443/cloudeng/cloud-build-env:1.9

stages:
  - build
  
build:
  stage: build
  tags:
    - docker
    - cloud
  only: 
    - cloud-master
  script:
    - go get -u github.com/golang/dep/cmd/dep
    - mkdir -p $GOPATH/src/github.com/weaveworks
    - cp -R $PWD $GOPATH/src/github.com/weaveworks
    - cd $GOPATH/src/github.com/weaveworks/cortex
    - make update-vendor
    - dep ensure
    - dep ensure --update
    - make BUILD_IN_CONTAINER=true IMAGE_PREFIX=docker-opts-intel.darkside.ea.com/cortex-
    