image: src.ent.ea.com:8443/cloudeng/cloud-build-env

stages:
  - build
  
build:
  stage: build
  tags:
    - docker
    - cloud
  only: 
    - cloud-master
  script:
    - dep ensure --update && make update-vendor
    - make
    